name: Astyle Code Formatter

on:
  pull_request:
    branches:
      - next  # Change the pull request branch name to 'next'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit hashes
        run: |
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"
          git fetch origin next

      - name: Install Astyle
        run: |
          sudo apt-get update
          sudo apt-get install -y astyle

      - name: Get modified files
        id: get_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} origin/next)"
          echo "Modified files:"
          cat ${{ steps.get_files.outputs.files }}

      - name: Format modified files
        run: |
          IFS=$'\n' read -r -d '' -a files <<< "${{ steps.get_files.outputs.files }}"
          for file in "${files[@]}"; do
            astyle --indent=force-tab=4 --suffix=none "${{ github.workspace }}/$file"
          done

      - name: Create commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Format code using Astyle"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
