name: Astyle Code Formatter

on:
  pull_request:
    branches:
      - next  # Change the pull request branch name to 'next'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Install Astyle
        run: |
          sudo apt-get update
          sudo apt-get install -y astyle

      - name: Get modified files
        id: get_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
          echo "git diff --name-only ${{ github.event.before }} ${{ github.event.after }}"

      - name: Format modified files
        run: |
          IFS=$'\n' read -r -d '' -a files <<< "${{ steps.get_files.outputs.files }}"
          for file in "${files[@]}"; do
            astyle --indent=force-tab=4 --suffix=none "$file"
          done

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'  # Update with Node.js 20 or the desired version

      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Format code using Astyle"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"

      - name: Create Notification
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const issueComment = `Hello! Astyle code formatter has formatted the code in this pull request. Please review the changes.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
